app {
  name = "Streaming Application"
  version = "1.0"
  sourceType = "KafkaConsumer"
  targetType = "KafkaProducer"
}
source {
  kafka {
    consumer {
      # ====================================
      # Mandatory Configs
      # ====================================
      bootstrap.servers = "bootstrap.servers=65.2.187.228:9092,13.235.238.222:9092"
      groupId = "1"
      keyDeserializer = "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer = "org.apache.kafka.common.serialization.StringDeserializer"
      topicName = "topic-name"

      # ====================================
      # Important Optional Configs
      # ====================================
      enableAutoCommit = false
      autoOffsetReset = "earliest"
      maxPollRecords = 500
      sessionTimeoutMs = 10000
      heartbeatIntervalMs = 3000
      maxPollIntervalMs = 300000
      fetchMinBytes = 1
      fetchMaxWaitMs = 500
      requestTimeoutMs = 30000
      retryBackoffMs = 100
      isolationLevel = "read_committed"
    }
  }
}

target {
  kafka {
    producer {
      # ====================================
      # Mandatory Configs
      # ====================================

      bootstrapServers = "bootstrap.servers=65.2.187.228:9092,13.235.238.222:9092"
      keySerializer = "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer = "org.apache.kafka.common.serialization.StringSerializer"
      topicName = "topic-name"

      # ====================================
      # Important Optional Configs
      # ====================================
      acknowledgements = "all"
      retries = 5
      batchSize = 16384
      compressionType = "snappy"
      clientId = "order-producer"

      retryBackoffMs = 100
      deliveryTimeoutMs = 120000
      requestTimeoutMs = 30000
      lingerMs = 10

      bufferMemory = 33554432

      maxInFlightRequestsPerConnection = 5
      enableIdempotence = true

      transactionalId = "order-transactional-producer"
      maxBlockMs = 60000
      metadataMaxAgeMs = 300000
    }
  }
}